name: Delete Old Files

on:
  push:
    branches: 
      - main

jobs:
  delete_old_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # 选择所需的Python版本

      - name: Install dependencies
        run: |
          pip install requests pytz

      - name: Run script
        run: python /main/py/py.py # 更新为正确的脚本路径

      - name: Commit and push changes (optional)
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add .
          git commit -m "Delete old files"
          git push
